### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by ankush** [chainer/backport#29]
Hello,

Currently, this repo does not have any license specified. It would be great if you could pick any FOSS license.

Thanks! 

Direct link to creation page: https://github.com/cupy/backport/community/license/new?branch=master

**Comment by kmaehashi** [comment]
Thanks for raising this! This backport script is considered as a part of CuPy so you can use it under MIT if you need.
To clarify that I'll add a license in #31.

**Comment by ankush** [comment]
Thanks @kmaehashi !
